### 
GET http://localhost:5000


###
post http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "irfan@test.dev",
    "password": "123123123"
}

###
post http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "haerunnas@test.dev",
    "password": "123123123"
}
